### ISSUE TITLE
problem when using mapall atlas

### ISSUE THREAD

**Issue by weiwei-wch** [netneurolab/neuromaps#102]
### Description of issue

Hi all,
    Thanks for making this fantastic tool!
    Recently when I use the mmpall atlas from Glasser et al. some issues come out. In detail, I fetch the mmpall (fslr, 32k) with netneurotools, then transfrom it to (fsaverage, 10k) and use it to do a parcellation-style null model generation,  there is an error said the number of the index of the parcellation is 361, which should be 360, I am not sure how this happen since this routine runs smoothly with shaefer parcellation. Here is the code I use and the error message:

```
import neuromaps
from netneurotools import datasets as nntdata
from neuromaps.parcellate import Parcellater
from neuromaps import transforms
from neuromaps.images import annot_to_gifti
from neuromaps import images, nulls

mmpall = nntdata.fetch_mmpall()
fsaverage5_mmpall = transforms.fslr_to_fsaverage(mmpall, '10k', method='nearest')
parc_gifti = fsaverage5_mmpall

parc_data = np.loadtxt('data.txt') # a 360*n nparray which contains the data

rotated1 = nulls.alexander_bloch(parc_data[:,0], atlas='fsaverage', density='10k', n_perm=1000, seed=7, parcellation=parc_gifti)
rotated2 = nulls.burt2020(parc_data[:,0], atlas='fsaverage', density='10k', n_perm=1000, seed=7, parcellation=parc_gifti, n_proc=20)
```

then this error occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weiw/.local/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 141, in alexander_bloch
    return load_data(data)[spins]
IndexError: index 361 is out of bounds for axis 0 with size 360
```

and when I use the burt2020 null model, this error occurs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weiw/.local/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 637, in burt2020
    return _make_surrogates(data, 'burt2020', atlas=atlas, density=density,
  File "/home/weiw/.local/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 530, in _make_surrogates
    for hdata, hdist, hind, hsl in genfunc(data, atlas, density,
  File "/home/weiw/.local/lib/python3.8/site-packages/neuromaps/nulls/nulls.py", line 435, in _surf_surrogates
    hdata = np.squeeze(data[idx])
IndexError: arrays used as indices must be of integer (or boolean) type
```

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by weiwei-wch** [comment]
Oh I just find that I need to do relabel_gifti since IDs of each hemisphere of mmpall are both 0-180
